development:
  host: 'http://localhost:4000'
  instagram_client_id: '2f9406ec657e411f91c63a690a5a0f91'
  instagram_client_secret: '35adea6e74c94bb5bf256f2ddcbf8962'
  tags: ['flowers', 'mountains']
  admin_user: 'craig'
  admin_password: 'tatsagram'
  copyright_text: 'Tatsagram 2012'