development:
  host: 'http://localhost:4000'
  instagram_client_id: '2f9406ec657e411f91c63a690a5a0f91'
  instagram_client_secret: '35adea6e74c94bb5bf256f2ddcbf8962'
  tags: ['tattoos', 'tattoo', 'apistagram', 'tattoosofinstagram']
  admin_user: 'craig'
  admin_password: 'tatsagram'
  copyright_text: 'Tatsagram 2012'
  hot_duration_in_hours: 24
  popular_duration_in_days: 365
  ads: 
    header: ['banner.gif', 'Banner Placeholder']
    home_page:
      whats_hot: ['728x90.jpg', 'Banner Placeholder']
      popular: ['728x90-2.jpg', 'Banner Placeholder']
    user_profile_page:
      left_section: ['250x250.jpg', 'Rectangle Placeholder']
    iphoto_page:
      left_section: ['banner2.gif', 'Banner Placeholder']
      right_section: ['336x280.jpg', 'Banner Placeholder']
