development:
  host: 'http://localhost:4000'
  admin_username: 'apistagram'
  admin_email: 'craig@craigmorrison.ca'
  instagram_client_id: 'd4c0d780aa374f28889e0e4dc28402eb'
  instagram_client_secret: '4834c8731b164da9b034faef50b88ead'
  tags: ['cakes', 'cakesta', 'apistagram', 'cakesofinstagram']
  admin_user: 'craig'
  admin_password: 'cakesta'
  copyright_text: 'Cakesta 2012'
  hot_duration_in_hours: 24
  popular_duration_in_days: 365
  hot: "What's Hot"
  newest: "Newest Shots"
  most_popular: "Most Popular"
  meta_tags:
    "Cakesta is an Instagram web viewer for photos of ONLY cakes. Check out some of the most popular cakes on Instagram, like them, save them and comment on them."
  title:
    default: "Cakesta - The only Instagram viewer dedicated to cakes :: #cakesta ::"
    hot: "Cakesta - Hottest Instagram photos of cakes :: #cakesta :: "
    newest: "Cakesta - Newest Instagram photos of cakes :: #cakesta :: "
    most_popular: "Cakesta - Most Popular Instagram photos of cakes :: #cakesta :: "
production:
  host: 'http://cakesta.com'
  admin_username: 'apistagram'
  admin_email: 'craig@craigmorrison.ca'
  instagram_client_id: '2f9406ec657e411f91c63a690a5a0f91'
  instagram_client_secret: '35b61a97b602469486f27af20db73ea7'
  tags: ['cakes', 'cakesta', 'apistagram', 'cakesofinstagram']
  admin_user: 'craig'
  admin_password: 'cakesta'
  copyright_text: 'Cakesta 2012'
  hot_duration_in_hours: 24
  popular_duration_in_days: 365
  hot: "What's Hot"
  newest: "Newest Shots"
  most_popular: "Most Popular"
  meta_tags:
    "Cakesta is an Instagram web viewer for photos of ONLY cakes. Check out some of the most popular cakes on Instagram, like them, save them and comment on them."
  title:
    default: "Cakesta - The only Instagram viewer dedicated to cakes :: #cakesta ::"
    hot: "Cakesta - Hottest Instagram photos of cakes :: #cakesta :: "
    newest: "Cakesta - Newest Instagram photos of cakes :: #cakesta :: "
    most_popular: "Cakesta - Most Popular Instagram photos of cakes :: #cakesta :: "    
  ads: 
    header: ['banner.gif', 'Banner Placeholder']
    home_page:
      whats_hot: ['728x90.jpg', 'Banner Placeholder']
      popular: ['728x90-2.jpg', 'Banner Placeholder']
    user_profile_page:
      left_section: ['250x250.jpg', 'Rectangle Placeholder']
    iphoto_page:
      left_section: ['banner2.gif', 'Banner Placeholder']
      right_section: ['336x280.jpg', 'Banner Placeholder']
